FROM mcr.microsoft.com/azure-sql-edge:1.0.7@sha256:7bc52119beea8a0ebc728e7e17cb971ca2a9d6bf091e92d8351508db2cc2574e

USER root
COPY containers/sqlserver/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY containers/sqlserver/init-db.sql /usr/local/bin/init-db.sql
RUN chmod +x /usr/local/bin/entrypoint.sh

USER mssql
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
