namespace Autheris.Domain.Model;

using System.Collections.Generic;
using Autheris.Domain.Common;

/// <summary>One catalog table as listed by the MCP <c>list_datasets</c> tool.</summary>
/// <param name="GraphQlField">Root query field of the dataset in the GraphQL API; null when the dataset is not in the GraphQL schema.</param>
public sealed record McpDatasetSummary(
    string Id,
    string? Description,
    string Sensitivity,
    int ColumnCount,
    string? GraphQlField = null);

/// <summary>A way to reach the gateway's data: protocol, HTTP method and URL. <see cref="Preferred"/> marks GraphQL.</summary>
public sealed record McpAccessPath(
    string Protocol,
    string Method,
    string Url,
    string Description,
    bool Preferred = false);

/// <summary>Result of the MCP <c>list_datasets</c> tool.</summary>
/// <param name="Guidance">How to query data: GraphQL first.</param>
/// <param name="Endpoints">All enabled protocols of the gateway, GraphQL first.</param>
public sealed record McpDatasetList(
    IReadOnlyList<McpDatasetSummary> Datasets,
    int Total,
    bool Truncated,
    string? Guidance = null,
    IReadOnlyList<McpAccessPath>? Endpoints = null);

/// <summary>A column the caller may see, as described by the MCP <c>describe_dataset</c> tool.</summary>
/// <param name="Type">Data type in the source database.</param>
/// <param name="GraphQlField">Field name in the GraphQL API (may differ from the column name).</param>
/// <param name="GraphQlType">GraphQL scalar of the field (String, Int, Long, Float, Decimal, Boolean).</param>
public sealed record McpDatasetColumn(
    string Name,
    string Type,
    string? Description,
    bool Sensitive,
    bool PrimaryKey,
    string? GraphQlField = null,
    string? GraphQlType = null);

/// <summary>A navigation from a dataset to a related dataset in the GraphQL API.</summary>
public sealed record McpGraphQlRelation(string Field, string Dataset, bool IsList);

/// <summary>How to query a dataset through GraphQL, the preferred query path.</summary>
public sealed record McpGraphQlAccess(
    string Endpoint,
    string QueryField,
    string TypeName,
    string FilterType,
    string OrderByType,
    string Arguments,
    string ExampleQuery,
    IReadOnlyList<McpGraphQlRelation> Relations);

/// <summary>A curated example query (golden query) for a dataset.</summary>
public sealed record McpDatasetExample(
    string Title,
    string? Description,
    string Query,
    string? Variables);

/// <summary>Result of the MCP <c>describe_dataset</c> tool.</summary>
public sealed record McpDatasetDescription(
    string Id,
    string Domain,
    string Schema,
    string Table,
    string? Description,
    string? LongDescription,
    string Sensitivity,
    bool RequiresApproval,
    IReadOnlyList<McpDatasetColumn> Columns,
    IReadOnlyList<McpDatasetExample> Examples,
    McpGraphQlAccess? GraphQl = null,
    IReadOnlyList<McpAccessPath>? OtherAccess = null);

/// <summary>GraphQL names of one catalog table, as generated by the catalog GraphQL schema.</summary>
public sealed record GraphQlTableMapping(
    TableIdentifier Table,
    string QueryField,
    string TypeName,
    string FilterType,
    string OrderByType,
    IReadOnlyList<GraphQlColumnMapping> Columns,
    IReadOnlyList<GraphQlRelationMapping> Relations);

public sealed record GraphQlColumnMapping(string ColumnName, string Field, string GraphQlType);

public sealed record GraphQlRelationMapping(string Field, TableIdentifier Target, bool IsList);

/// <summary>Result of the MCP <c>sample_rows</c> tool: rows as returned by the governed read path (masked, row filtered).</summary>
public sealed record McpDatasetSample(
    string Id,
    int RowCount,
    IReadOnlyList<IReadOnlyDictionary<string, object?>> Rows);
